---
- name: Create Vms
  
  hosts: all

  tasks:
    - name: Create terraform tfvars
      template:
        src: templates/nodes.tfvars.j2
        dest: "{{ terraform_path }}/nodes.tfvars"

    - name: Create cloud-init directory
      file:
        state: directory
        path: "{{ terraform_path }}/cloud-init"

    - name: Create ssh keys directory
      file:
        state: directory
        path: "{{ project_path }}/ssh_keys"

    - name: Generate ssh keys
      openssh_keypair:
        path: "{{ project_path }}/ssh_keys/id_{{ item.name }}_rsa"
        type: rsa
        size: 4096
      loop: "{{ nodes }}"

    - name: Create user-data for cloud init
      template:
        src: templates/user-data.j2
        dest: "{{ terraform_path }}/cloud-init/user-data-{{ item.name }}"
      loop: "{{ nodes }}"

    - name: Deploy
      terraform:
        project_path: "{{ terraform_path }}"
        state: present
        variables_file: "{{ terraform_path }}/nodes.tfvars"
      register: tf_out

    - name: Write VM list
      template:
        src: vms.j2
        dest: "{{ project_path }}/vms"
