---
- hosts: all

  tasks:
    - name: Destroy VMs
      terraform:
        project_path: "{{ terraform_path }}"
        state: absent
        variables_file: "{{ terraform_path }}/nodes.tfvars"

    - name: Delete project directories
      file:
        state: absent
        path: "{{ item }}"
      loop:
        - "{{ project_path }}"
        - "{{ terraform_path }}"
        - "{{ cloudinit_path }}"
        - "{{ ssh_keys_path }}"
