---
- name: Assign hosts to groups

  hosts: all

  tasks:
    - name: Assign hosts to groups
      add_host:
        name: "{{ item }}"
        groups:
          - "{{ hostvars[item].type }}"
      loop: "{{ groups['all'] }}"
      changed_when: false


- name: Provision package repository
  
  hosts: repository

  roles:
    - repository


- name: Provison common

  hosts:
    - k8s_control
    - k8s_worker
    - storage

  roles:
    - common


- name: Provision storage nodes

  hosts:
    - storage

  roles:
    - storage


- name: Provision kubernetes nodes

  hosts:
    - k8s_control
    - k8s_worker

  roles:
    - k8s_common


- name: Provision kubernetes control nodes

  hosts: k8s_control

  roles:
    - k8s_control

- name: Provision kubernetes worker nodes
  
  hosts: k8s_worker

  roles:
    - k8s_worker
