---
- name: Assign hosts to groups

  hosts: all

  tasks:
    - name: Assign hosts to groups
      add_host:
        name: "{{ item }}"
        groups:
          - "{{ hostvars[item].type }}"
      loop: "{{ groups['all'] }}"
      changed_when: false



- name: Reset kubernetes nodes

  hosts:
    - k8s_control
    - k8s_worker

  tasks:
    - name: kubeadm reset
      command: kubeadm reset
      become: yes

    - name: reset firewall
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - iptables
        - ip6tables
      become: yes
