---
- name: Copy pacman.conf
  template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
  become: yes

- name: Install requiered packages
  pacman:
    name: "{{ packages }}"
    state: present

- name: Set firewall configuration
  template:
    src: iptables.rules.j2
    dest: /etc/iptables/iptables.rules
  become: yes
  notify: "restart firewall"

- name: start firewall
  service:
    name: iptables
    enabled: yes
    state: started
  become: yes
